-- MySQL Script generated by MySQL Workbench
-- Thu Apr 15 22:36:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema materialgestor
-- -----------------------------------------------------
DROP DATABASE `materialgestor`;

CREATE DATABASE `materialgestor`;

USE `materialgestor`;

-- -----------------------------------------------------
-- Table `materialgestor`.`DOCENTES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materialgestor`.`DOCENTES`;

CREATE TABLE IF NOT EXISTS `materialgestor`.`DOCENTES` (
    `id_docente` INT NOT NULL,
    `nombre_completo` VARCHAR(60) NULL,
    `correo` VARCHAR(60) NULL,
    `clave` VARCHAR(45) NULL,
    `anio_nacimiento` DATETIME NULL,
    `areas_conocimiento` VARCHAR(45) NULL,
    `materia` VARCHAR(45) NULL,
    PRIMARY KEY (`id_docente`)
);

-- -----------------------------------------------------
-- Table `materialgestor`.`MATERIALES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materialgestor`.`MATERIALES`;

CREATE TABLE IF NOT EXISTS `materialgestor`.`MATERIALES` (
    `id` INT NOT NULL,
    `titulo_material` VARCHAR(45) NULL,
    `link_material` VARCHAR(100) NULL,
    `fecha_material` VARCHAR(45) NULL,
    `link_archivo_material` VARCHAR(100) NULL,
    `DOCENTES_id_docente` INT NOT NULL,
    `publicado` TINYINT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_MATERIALES_DOCENTES` FOREIGN KEY (`DOCENTES_id_docente`) REFERENCES `materialgestor`.`DOCENTES` (`id_docente`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

-- -----------------------------------------------------
-- Table `materialgestor`.`RECONOCIMIENTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materialgestor`.`RECONOCIMIENTOS`;

CREATE TABLE IF NOT EXISTS `materialgestor`.`RECONOCIMIENTOS` (
    `id_reconocimiento` INT(10) NOT NULL,
    `DOCENTES_id_docente` INT NOT NULL,
    `persona_que_otorga` VARCHAR(60) NULL,
    `persona_que_recibe` VARCHAR(60) NULL,
    `entidada_otorga` VARCHAR(60) NULL,
    `razon` VARCHAR(250) NULL,
    `anio_reconocimento` DATETIME NULL,
    PRIMARY KEY (`id_reconocimiento`),
    CONSTRAINT `fk_RECONOCIMIENTOS_DOCENTES1` FOREIGN KEY (`DOCENTES_id_docente`) REFERENCES `materialgestor`.`DOCENTES` (`id_docente`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

-- INSERTS